### ISSUE TITLE
No spatial sequence data

### ISSUE THREAD

**Issue by liufuyan2016** [ZJUFanLab/bulk2space#1]
I only have scRNA-seq and bulked RNA-seq. Could  I use this tools ?

**Comment by ForwardYang98** [comment]
Do you mean just deconvolute the bulk RNA-seq data to single cell?

**Comment by liufuyan2016** [comment]
yes! Could be used ?

**Comment by ForwardYang98** [comment]
Of course you can. Bulk2Space could deconvolute the bulk RNA-seq data to single cell just via the deconvolution procedure, and you can get the deconvoluted single cell gene expression matrix in the `output_data/../predata` folder. We will update Bulk2Space and provide more application tutorials in the future, or you can just explore it by yourself right now.
