### ISSUE TITLE
model.train_df_and_spatial_deconvolution error

### ISSUE THREAD

**Issue by zhangqi234** [ZJUFanLab/bulk2space#10]
Hi, thanks for coming up with this useful tool. 
When I conducted the model.train_df_and_spatial_deconvolution function to decompose ST data into spatially resolved single-cell transcriptomics data, I found the error like "pandas.errors.MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False". I don't know what caused this error.

![1668324980352](https://user-images.githubusercontent.com/62313781/201511233-31c79b96-5834-47ab-a766-cd1b18ec64b9.png)

**Comment by AlexUOM** [comment]
Hi,
I am also experiencing an error with the model.train_df_and_spatial_deconvolution function.
In my case the error is `ValueError: no types given` as you can see below:
![Immagine 2022-11-13 132113](https://user-images.githubusercontent.com/105374372/201523864-0de85c6b-ba35-449d-b7b2-bcf1d3379260.png)


I am running the pdac tutorial with all the pre-provided data. 
Hope you can help with this.

**Comment by ForwardYang98** [comment]
> Hi, thanks for coming up with this useful tool. When I conducted the model.train_df_and_spatial_deconvolution function to decompose ST data into spatially resolved single-cell transcriptomics data, I found the error like "pandas.errors.MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False". I don't know what caused this error.
> 
> ![1668324980352](https://user-images.githubusercontent.com/62313781/201511233-31c79b96-5834-47ab-a766-cd1b18ec64b9.png)

Hi, it seems there are some errors in your data format. You could refer to the [Tutorial Handbook](https://github.com/ZJUFanLab/bulk2space/blob/main/tutorial/handbook.md) to check the format of input again.

**Comment by ForwardYang98** [comment]
> ValueError: no types given

Hi, I have run the PDAC tutorial successfully again just now.   I guess there are some errors in the format of your data, maybe you could check it by following the [Tutorial Handbook](https://github.com/ZJUFanLab/bulk2space/blob/main/tutorial/handbook.md)

**Comment by AlexUOM** [comment]
> Hi, I have run the PDAC tutorial successfully again just now. I guess there are some errors in the format of your data, maybe you could check it by following the [Tutorial Handbook](https://github.com/ZJUFanLab/bulk2space/blob/main/tutorial/handbook.md)


Thank you for your feedback. I double checked again the format of the data as you adviced and everything is looking fine. 

Here is a quick look of how the 4 input files for model.train_df_and_spatial_deconvolution look like (using `.head()`)
generate_sc_data:
![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201637948-d4118625-f5a2-4660-99d5-521ac805d133.png)

generate_sc_meta:
![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201639718-3748cf05-2eb5-4666-9210-4fb6528c111d.png)

st_data.csv:
![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201639944-111d4c8d-8e34-4100-8baf-13bd49f7282d.png)

st_meta.csv:
![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201640042-94829e1f-fe87-47f4-9f3d-2a54b930a3ab.png)

Is this what they are supposed to look like?
I suspect the files that throw the error are the st reference files (either st_meta or st_data, not sure which one).

**Comment by ForwardYang98** [comment]
> > Hi, I have run the PDAC tutorial successfully again just now. I guess there are some errors in the format of your data, maybe you could check it by following the [Tutorial Handbook](https://github.com/ZJUFanLab/bulk2space/blob/main/tutorial/handbook.md)
> 
> Thank you for your feedback. I double checked again the format of the data as you adviced and everything is looking fine.
> 
> Here is a quick look of how the 4 input files for model.train_df_and_spatial_deconvolution look like (using `.head()`) generate_sc_data: ![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201637948-d4118625-f5a2-4660-99d5-521ac805d133.png)
> 
> generate_sc_meta: ![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201639718-3748cf05-2eb5-4666-9210-4fb6528c111d.png)
> 
> st_data.csv: ![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201639944-111d4c8d-8e34-4100-8baf-13bd49f7282d.png)
> 
> st_meta.csv: ![Immagine 2022-11-14 103118](https://user-images.githubusercontent.com/105374372/201640042-94829e1f-fe87-47f4-9f3d-2a54b930a3ab.png)
> 
> Is this what they are supposed to look like? I suspect the files that throw the error are the st reference files (either st_meta or st_data, not sure which one).

According to the screenshots you provided, the column number of st_data (428 columns) is not same as the row number of st_meta  (429 rows). The spots in st_data and st_meta are supposed to be same for Bulk2Space, as shown below:
`st_data.shape  
(19104, 428)  
st_meta.shape  
(428, 3)`

**Comment by AlexUOM** [comment]
The number of rows and columns in the files is different you are correct. 
To resume, st_meta has **428 rows** x 4 columns:
![Immagine 2022-11-14 155021](https://user-images.githubusercontent.com/105374372/201704357-3a517901-a077-4e76-8273-49bdcfc0131c.png)

...while st_data has 19104 rows x **429 columns** :
![Immagine 2022-11-14 155137](https://user-images.githubusercontent.com/105374372/201704641-48b424da-f2b3-4193-9762-a66ded8c11f9.png)

The reason why st_data has an extra column is because it counts the first column (without a name) that contains the gene names. Could this be the reason of the error?

**Comment by ForwardYang98** [comment]
> The number of rows and columns in the files is different you are correct. To resume, st_meta has **428 rows** x 4 columns: ![Immagine 2022-11-14 155021](https://user-images.githubusercontent.com/105374372/201704357-3a517901-a077-4e76-8273-49bdcfc0131c.png)
> 
> ...while st_data has 19104 rows x **429 columns** : ![Immagine 2022-11-14 155137](https://user-images.githubusercontent.com/105374372/201704641-48b424da-f2b3-4193-9762-a66ded8c11f9.png)
> 
> The reason why st_data has an extra column is because it counts the first column (without a name) that contains the gene names. Could this be the reason of the error?

Yes. You could set the first column (gene names) as the index and then try it again.
