### ISSUE TITLE
the question of "quick start" section

### ISSUE THREAD

**Issue by coconutll** [ZJUFanLab/bulk2space#11]
Dear professors,
          We are very sorry to bother you. We recently downloaded the bulk2space and used the test data of demo1, but we don't know why there are no result output, and we don't know whether the data are written normally. After operation, the Bulk2space-1.0.0-Py3.8egg displayed empty. Some information are as follows. I would wonder if you can help check it in your busy schedule or if there is any other step guidance.
![bulk2space](https://user-images.githubusercontent.com/118164450/201612891-62c9e687-fcc4-465a-a9c7-511c2186f066.png)

**Comment by ForwardYang98** [comment]
Hi, we recommend running Bulk2Space on the Jupyter Notebook after installing it, and then you can run the code step by step and check the output of each setp.

**Comment by coconutll** [comment]
Thank you for your advice. I will download this and try it.
