### ISSUE TITLE
Questions about input data requirements

### ISSUE THREAD

**Issue by Archi6** [ZJUFanLab/bulk2space#16]
Hi, author,

Thank you very much for sharing this great tool.

I would like to apply bulk2space to determine the location in the tissue of several cell types in different bulk data. But I still have some confusion about this tool.

 When using bulk2space, do the bulk RNA-seq, scRNA-Seq, and spatial data have to be from the same tissue (or consecutive slice of the same tissue)? If the bulk RNA-seq, scRNA-Seq, and spatial data can be taken from different tissues, which tissue does the spatial results generated in the mapping step belong to, the spatial data or the bulk RNA-seq data?

**Comment by SpaTrek** [comment]
Hi, user,

Thank you for using Bulk2Space.

First, paired data are not so necessary for Bulk2Space, and we have described this in detail in the manuscript. However, you are not encouraged to map brain bulk data to a heart spatial reference, or something like that. 

Second, basically, the results are derived from bulk data. Specifically, bulk data are first deconvolved into single-cell data. We calculate the clustering space for each cell type and generate single-cell data within the given clustering space using beta-VAE. The generated single-cell data have a high similarity with the bulk data. Then, we map each generated single cell to the spatial reference.

In addition, it depends on your purpose when using Bulk2Space. If you want to reanalyze the bulk data with spatial resolution, Bulk2Space is your best choice. If you want to analyze the spatial heterogeneity of the spatial data, you can use the second step of Bulk2Space, and you can obtain deconvolved spatial data with single-cell resolution.

I suggest you just express your main idea for using Bulk2Space and we can provide a more detailed explanation.

Best regards.

**Comment by Archi6** [comment]
Thank you for your patient response. I'm a beginner, and I am not sure if I have correctly understood your manuscript.

I have a lot of bulk data with only one spatial reference and one single-cell reference. I  want to obtain the spatial distribution of cells in the tissue where the bulk data comes from, to determine if the closer the cell type A is to cell type B, the more cell type A cells there are.

I am a bit confused because I thought that the coordinates provided by the spatial reference belong to cells in the ST data, and the mapping step just embeds cell types onto the coordinates based on gene expression similarity. Therefore, shouldn't the final result be ST data at cellular resolution, but bulk data at spatial resolution?

**Comment by Archi6** [comment]
您好，感谢您的回复。因为用英语我不太能准确表达我的意思，所以我还是用中文去解释我的问题，希望您不要介意。

我想用bulk2spce来判断不同bulk数据中各细胞的位置，希望能得到两种细胞类型间距离与数量的关系，比如是否细胞类型A离细胞类型B越近，细胞类型A的数量就越多。以下是我的一点疑问：

1. 我对bulk2space的理解是， deconvolution这一步提供了细胞类型，st数据提供了细胞的坐标，mapping这一步通过基因表达相似性将细胞映射到对应的坐标上。如果我对这个方法没有理解错的话，那最后得到的结果不应该是使得st数据达到了单细胞分辨率吗，为什么会是bulk数据获得了空间分辨率呢？

2. 我尝试用bulk2space来跑我的数据，我提供的sc_meta中有五种细胞，但是最后的结果只有两种细胞，请问这是因为我使用的spatial reference不够好吗。

3. 请问如果sc_meta的细胞数量比st数据的spot少很多，会对结果有不好的影响吗？

希望能得到您的回复，祝您科研顺利，生活愉快！

**Comment by SpaTrek** [comment]
> 

1. Bulk数据通过解卷积变成单细胞之后，再映射到空间中，所以可以理解为Bulk数据获得了空间信息。这里的单细胞是β-VAE以单细胞数据为参考图谱生成的，所以可以认为是Bulk数据的分解。最终得到的数据也是Bulk转成了单细胞空间转录组数据；如果想分析空间转录组中的细胞组成，可以用Bulk2Space的第二步进行分析，但是最好是配对的数据，即正常单细胞映射到正常空间，疾病单细胞映射到疾病空间。
2. Bulk2Space会先分析一下不同细胞类型的比例，所以当提供的单细胞数据中有的细胞类型预测的比例为0时，就不会生成这一类细胞。
3. Bulk2Space可以设置生成细胞的数量，很少出现比spot少的情况，你可以看看具体参数。
还有任何问题，随时留言

**Comment by yuchen345** [comment]
@SpaTrek 廖老师您好 我有几个问题想咨询您
1. 如果将不同样本bulk数据（如来源不同病人）映射到同一个空间组织上，细胞类型和基因表达是否有差异？
2. 单细胞reference是否可以是整合多样本来源的单细胞集，比如多个病人的肿瘤样本单细胞merge，是否会影响细胞比例？
3. 细胞注释需要越详细越好吗？需不需要对大类细胞再划分小类注释？

**Comment by SpaTrek** [comment]
> @SpaTrek 廖老师您好 我有几个问题想咨询您
> 
> 1. 如果将不同样本bulk数据（如来源不同病人）映射到同一个空间组织上，细胞类型和基因表达是否有差异？
> 2. 单细胞reference是否可以是整合多样本来源的单细胞集，比如多个病人的肿瘤样本单细胞merge，是否会影响细胞比例？
> 3. 细胞注释需要越详细越好吗？需不需要对大类细胞再划分小类注释？

1. 应该是可以的，欢迎尝试。细胞类型和基因表达我认为应该会有差异
2. 可以的
3. 具体取决于你的目标任务，可以多尝试几下，目前bulk2space生成细胞跟类型无关，不过会根据细胞类型的预测比例去生成，理论上会有差别，时间上还是要多实践
