### ISSUE TITLE
Need Nvidia driver

### ISSUE THREAD

**Issue by millersan** [ZJUFanLab/bulk2space#2]
scipy need Nvida driver, but it is hard to install without root in ubuntu.

**Comment by ForwardYang98** [comment]
We are sorry that the installation protocol doesn’t work for you. We will try other ways to make it available to users without installation.

**Comment by SpaTrek** [comment]
you can try it now!!! the latest bulk2space allows implementation without gpu.

**Comment by SpaTrek** [comment]
you can try it now!!! the latest bulk2space allows implementation without gpu.
