### ISSUE TITLE
Cannot import CascadeForestClassifier from deepforest

### ISSUE THREAD

**Issue by sarah-chapin** [ZJUFanLab/bulk2space#5]
I am running the bulk2space.py script via Python 3.8.5. The deepforest package is installed and imports successfully, but I am still receiving the following error message:

ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest'

I would appreciate any help you could offer.

**Comment by ForwardYang98** [comment]
Hi, you need to install the correct version of deepforest package. Make sure the version is `deep-forest==0.1.5`

**Comment by sarah-chapin** [comment]
Thank you, this resolved the issue.
