### ISSUE TITLE
Preproccessed PDAC data

### ISSUE THREAD

**Issue by AlexUOM** [ZJUFanLab/bulk2space#9]
Hello,

I am trying to understand how to use bulk2space by going though the tutorials. I am currently going though the first tutorial with the PDAC datasets.
I would like to know how you generated the preprocessed files "st_data" and "st_meta".

I went to the original data from Moncada et al. (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE111672) but I don't know which files you used from there to make the above preprocessed files. Could you clarify that and explain a bit more in detail how you generated "st_data" and "st_meta"? This will be helpful to understand how to process other reference datasets.

**Comment by ForwardYang98** [comment]
Hi,
In this tutorial, we applied the PDAC-A ST1 data (GSM3036911) as the spatial reference. For all scRNA-seq and spatially resolved transcriptomics datasets, the raw counts were normalized using the global-scaling normalization method “LogNormalize” by Seurat (version 4.0.4). 
Becides, you could get more detailed description of analysis in our manuscript.

**Comment by AlexUOM** [comment]
Hi,
Thank you for your reply, it makes things clearer. I managed to reproduce the pdac "st_data" but it isn't exactly the same as the one you provided.

In the PDAC-A ST1 data there are a couple of files available:

```
GSM3036911.tsv.gz | 1.8 Mb 
GSM3036911_PDAC-A-ST1-Cy3.jpg.gz | 661 b 
GSM3036911_PDAC-A-ST1-HE.jpg.gz | 280.1 Mb 
GSM3036911_PDAC-A-ST1-filtered.txt.gz | 717.0 Kb
```
I am guessing you used `GSM3036911.tsv.gz` to create "st_data"?

**Comment by ForwardYang98** [comment]
I'm sorry I didn't make it clear. We used `GSM3036911_PDAC-A-ST1-filtered.txt.gz` rather than `GSM3036911.tsv.gz` to create the `st_data`.
And the coordinates information of each spot could be obtained from the column names of `GSM3036911_PDAC-A-ST1-filtered.txt.gz`  and then you could create `st_meta`.
Hope it would help you.

**Comment by AlexUOM** [comment]
Thanks that's exactly what I needed to know!
